### PR TITLE
Added Initial Readme

### PR DESCRIPTION
**Pull request by Smrosner**

### CODE REVIEW

**Review by kevinalexliu — COMMENTED** [review]
looks great

**Review by jackzhen1996 — APPROVED** [review]
looks good

**Review by melliottgithub — CHANGES_REQUESTED** [review]
Be more specific about changes

**Comment by Smrosner** [comment]
Update to request: add file structure changes to Compare component. @melliottgithub

**Review by melliottgithub — APPROVED** [review]

**Pull request merged**
